Repository forntoh/LcdMenu, pull requests merged in 2025-01, with the labels that each got.

#284 Fix SSD1803A I2C LCD adapter cursor positioning and renderer
  examples/SSD1803A_I2C/SSD1803A_I2C.ino
  src/display/SSD1803A_I2CAdapter.h
Labels: bugfix

#286 Fix ItemToggle Duplicate Item When Refreshing Menu in Callback
  .github/workflows/lint_check.yml
  src/ItemToggle.h
Labels: bugfix

#285 Add ItemValue template class and polling support for menu items
  .github/workflows/compile-arduino.yml
  diagram.json
  docs/source/overview/items/index.rst
  docs/source/overview/items/item-value.rst
  examples/ItemValue/ItemValue.ino
  examples/RTOS/RTOS.ino
  platformio.ini
  src/ItemValue.h
  src/LcdMenu.cpp
  src/LcdMenu.h
  src/MenuItem.h
  src/MenuScreen.cpp
  src/MenuScreen.h
  src/widget/BaseWidget.h
Labels: feature

#290 Display timeout works only when a draw operation happens
  src/LcdMenu.cpp
  src/MenuScreen.cpp
Labels: bugfix

#296 Support for analog button array
  docs/source/overview/control/analogButton.rst
  docs/source/overview/control/images/Keypad_shield.jpeg
  docs/source/overview/control/images/analog_buttons_example_schematic.png
  docs/source/overview/control/index.rst
  examples/KeypadShield/KeypadShield.ino
  src/input/AnalogButtonAdapter.h
Labels: feature

#298 Remove deprecated range item
  src/ItemFloatRange.h
  src/ItemIntRange.h
  src/ItemRangeBase.h
Labels: chore

#299 Update WidgetBool process method to restrict value changes to edit mode
  src/widget/WidgetBool.h
Labels: bugfix

#301 Move shared deps into [env]
  platformio.ini
Labels: chore

#297 Feauture/use index for widget list
  docs/source/overview/items/item-widget.rst
  examples/ButtonWithRotaryAdapter/ButtonWithRotaryAdapter.ino
  examples/KeypadShield/KeypadShield.ino
  examples/List/List.ino
  examples/SimpleRotary/SimpleRotary.ino
  examples/Widgets/Widgets.ino
  src/widget/WidgetList.h
  test/List.test.yml
  test/Widgets.test.yml
Labels: enhancement
