Repository forntoh/LcdMenu, pull requests merged in 2025-03, with the labels that each got.

#315 Allow dynamic assignment (use of reference values) to WIDGETS
  .github/workflows/compile-arduino.yml
  examples/UseByRef/UseByRef.ino
  src/BaseItemManyWidgets.h
  src/widget/BaseWidgetValue.h
  src/widget/WidgetBool.h
  src/widget/WidgetList.h
  src/widget/WidgetRange.h
  test/UseByRef.test.yml
Labels: enhancement, feature

#319 Fixes crash on ESP when deactivating arrows
  src/renderer/CharacterDisplayRenderer.cpp
Labels: bugfix

#323 Added usage documentation for reference values feature
  docs/source/overview/widgets/widget-bool.rst
  docs/source/overview/widgets/widget-list.rst
  docs/source/overview/widgets/widget-range.rst
Labels: documentation

#324 Add support for dynamically (at runtime) created menus and widgets
  .github/workflows/arduino_ci.yml
  .github/workflows/compile-arduino.yml
  docs/source/overview/getting-started.rst
  docs/source/overview/items/item-widget.rst
  docs/source/overview/items/list.rst
  docs/source/overview/items/range.rst
  docs/source/overview/items/submenu.rst
  docs/source/reference/migration/index.rst
  docs/source/reference/migration/v5.9.0-v5.10.0.rst
  examples/ButtonWithRotaryAdapter/ButtonWithRotaryAdapter.ino
  examples/DynamicMenu/DynamicMenu.ino
  examples/KeypadShield/KeypadShield.ino
  examples/List/List.ino
  examples/SimpleRotary/SimpleRotary.ino
  examples/UseByRef/UseByRef.ino
  examples/Widgets/Widgets.ino
  platformio.ini
  src/BaseItemManyWidgets.h
  src/ItemList.h
  src/ItemSubMenu.h
  src/ItemValue.h
  src/ItemWidget.h
  src/MenuItem.h
  src/MenuScreen.cpp
  src/MenuScreen.h
  src/utils/custom_printf.h
  src/utils/std.h
  src/widget/BaseWidget.h
  src/widget/WidgetList.h
  test/LcdMenu.cpp
Labels: feature

#330 Fix MenuScreen draw loop to prevent out-of-bounds access by limiting iteration to available items
  src/MenuScreen.cpp
Labels: bugfix
