Repository forntoh/LcdMenu, pull requests merged in 2025-06, with the labels that each got.

#356 Fix renderer timeout logic
  src/renderer/MenuRenderer.h
Labels: codex

#361 Update lint_check.yml
  .github/workflows/lint_check.yml
Labels: chore

#359 Added isEnabled method in LcdMenu Class
  src/LcdMenu.cpp
  src/LcdMenu.h
Labels: enhancement

#357 Fix cursor bound in MenuScreen
  src/MenuScreen.cpp
Labels: bugfix, codex

#362 Fix doc text in LcdMenu
  src/LcdMenu.h
Labels: documentation, codex

#364 Add ItemValue polling unit test
  test/ItemValue.cpp
Labels: chore, codex

#365 Add MenuScreen unit tests
  test/MenuScreenTest.cpp
Labels: chore, codex

#370 Add repeat support for button adapters
  .scripts/prepare_example.py
  .scripts/prepare_workflow.py
  docs/source/overview/control/analogButton.rst
  docs/source/overview/control/button.rst
  examples/ButtonAdapter/ButtonAdapter.ino
  examples/KeypadShield/KeypadShield.ino
  src/input/AnalogButtonAdapter.h
  src/input/ButtonAdapter.h
  src/input/RepeatState.h
  test/ButtonAdapter.test.yml
  test/README.md
Labels: feature, codex

#372 Fix MenuScreen draw bounds
  src/MenuScreen.cpp
  test/MenuScreenTest.cpp
Labels: bugfix

#378 Fix removeWidget deletion
  src/BaseItemManyWidgets.h
Labels: enhancement

#380 Add destructor for arrow icons
  src/renderer/CharacterDisplayRenderer.cpp
  src/renderer/CharacterDisplayRenderer.h
Labels: codex

#391 Update wokwi_ci.yml
  .github/workflows/wokwi_ci.yml
Labels: chore
